### ISSUE TITLE
Issue running the docker command

### ISSUE THREAD

**Issue by potgieterdl** [rjpearce/sofar2mqtt-python#1]
Using the example from the setup guide and running 
` sudo docker run --name sofar2mqtt -e MQTT_HOST=x.x.x.x -e MQTT_PORT=1883 -e USERNAME=mqtt_user -e PASSWORD=xxxxxx -e CONFIG_FILE=sofar-hyd-ep.json -e TTY_DEVICE=/dev/ttyUSB0 --device=/dev/ttyUSB0 rpearce/sofar2mqtt-python:latest`

I get the exec error 
`exec /usr/local/bin/python: exec format error`

This is a fresh install of ubuntu on a RPI4 with official docker setup. Nothing else.

Thanks

**Comment by rjpearce** [comment]
Thanks for letting me know. I have been having a world of fun trying to get multiarch containers to actually work.

Can you try this one: ```docker pull rpearce/sofar2mqtt-python:arm-latest```

**Comment by rjpearce** [comment]
I bought a Raspberry Pi to test this out, please use:

[arm-latest](https://hub.docker.com/layers/rpearce/sofar2mqtt-python/arm-latest/images/sha256-4d241a5c12632d57c1687f302a999f4e4410d79a90bcc4a8e217fe8027f94c19?context=repo)
