### ISSUE TITLE
sofar2mqtt-python doiesnt start anymore

### ISSUE THREAD

**Issue by linky67** [rjpearce/sofar2mqtt-python#19]
Hello,

I am getting an error since today.
I got a state "Emergency Error" on the Sofar state and I was not able to write anything anymore. Seems there was temporary a low frequency statement but the inverter is working fine. But since then I was not able to change the state anymore on the Sofar and data froze.

Restarted the container on my Synology and the container doesnt want to restart anymore with an error.
In case, I restarter my inverter but didnt solved the issue.

Attached the logs I have. I was maybe expecting a communication issue but seems to be ok, all cabling and usb stick is properly plugged and detected by my synology with drivers and co.

When it boots, I have those mqtt poping in the channel :
Topic: sofar/desired_powerQoS: 0
0
Topic: sofar/pv_total_powerQoS: 0
0
Topic: sofar/gridQoS: 0
0

Then the error occur as below:
[rpearce-sofar2mqtt-python-1.csv](https://github.com/rjpearce/sofar2mqtt-python/files/15101840/rpearce-sofar2mqtt-python-1.csv)

2024/04/25 00:34:58 | stdout | KeyError: 'serial_number'
-- | -- | --
2024/04/25 00:34:58 | stdout | ~~~~~~~~~^^^^^^^^^^^^^^^^^
2024/04/25 00:34:58 | stdout | sn = self.data['serial_number']
2024/04/25 00:34:58 | stdout | File "/opt/sofar2mqtt/sofar2mqtt-v2.py", line 286, in publish_mqtt_discovery
2024/04/25 00:34:58 | stdout | self.publish_mqtt_discovery()
2024/04/25 00:34:58 | stdout | File "/opt/sofar2mqtt/sofar2mqtt-v2.py", line 366, in main
2024/04/25 00:34:58 | stdout | sofar.main()
2024/04/25 00:34:58 | stdout | File "/opt/sofar2mqtt/sofar2mqtt-v2.py", line 576, in main
2024/04/25 00:34:58 | stdout | ^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024/04/25 00:34:58 | stdout | return __callback(*args, **kwargs)
2024/04/25 00:34:58 | stdout | File "/usr/local/lib/python3.12/site-packages/click/core.py", line 760, in invoke
2024/04/25 00:34:58 | stdout | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024/04/25 00:34:58 | stdout | return ctx.invoke(self.callback, **ctx.params)
2024/04/25 00:34:58 | stdout | File "/usr/local/lib/python3.12/site-packages/click/core.py", line 1404, in invoke
2024/04/25 00:34:58 | stdout | ^^^^^^^^^^^^^^^^
2024/04/25 00:34:58 | stdout | rv = self.invoke(ctx)
2024/04/25 00:34:58 | stdout | File "/usr/local/lib/python3.12/site-packages/click/core.py", line 1055, in main
2024/04/25 00:34:58 | stdout | ^^^^^^^^^^^^^^^^^^^^^^^^^^
2024/04/25 00:34:58 | stdout | return self.main(*args, **kwargs)
2024/04/25 00:34:58 | stdout | File "/usr/local/lib/python3.12/site-packages/click/core.py", line 1130, in __call__
2024/04/25 00:34:58 | stdout | main()
2024/04/25 00:34:58 | stdout | File "/opt/sofar2mqtt/sofar2mqtt-v2.py", line 580, in <module>
2024/04/25 00:34:58 | stdout | Traceback (most recent call last):
2024/04/25 00:34:58 | stdout | 2024-04-24 22:34:58,894 - INFO - Modbus Requests: 128 Retries: 128 (100.0%) Failures: 64 (25.0%)
2024/04/25 00:34:20 | stdout | 2024-04-24 22:34:20,198 - INFO - Subscribing to sofar/rw/desired_power
2024/04/25 00:34:20 | stdout | 2024-04-24 22:34:20,198 - INFO - Subscribing to sofar/rw/time_of_use_charge_soc
2024/04/25 00:34:20 | stdout | 2024-04-24 22:34:20,197 - INFO - Subscribing to sofar/rw/energy_storage_mode
2024/04/25 00:34:20 | stdout | 2024-04-24 22:34:20,197 - INFO - Subscribing to homeassistant/status
2024/04/25 00:34:20 | stdout | 2024-04-24 22:34:20,197 - INFO - MQTT Connection Accepted.
2024/04/25 00:34:19 | stdout | 2024-04-24 22:34:19,999 - INFO  MQTT connecting to broker 192.168.1.XX port 1883 with auth user XX
(XX on purpose)

Thank you for your support.

**Comment by linky67** [comment]
Hello, the issue has been found and was tricky. It was my usb stick that died, cabling and co was ok.
This can be closed but maybe could be interesting to improve the debugging as the error is not linked to a connection issue?

In any case, I take the opportunity to thank you so much for your work, I am so happy to be able to remotely control my inverter thanks to you :-)

**Comment by rjpearce** [comment]
@linky67 thanks for letting me know. I have added a fix for the issue. It looks like the request to get the serial number failed and that is what causes the exception. It will now log that as an error and then try again next time around. Let me know if you have any more issues.

**Comment by linky67** [comment]
Thanks @rjpearce, so far nothing came back but I will perform some crashing tests in the coming weeks and come back to share how it behaves.
