### ISSUE TITLE
Grid value is not accurate when low active power on sofar HYD-XXX-EP

### ISSUE THREAD

**Issue by Tof973** [rjpearce/sofar2mqtt-python#7]
As grid power is a substarct of load_power - active_power it gives unwated results when active_power is very low or 0 .
active_power is reported sometimes less than zero which give a higher grid power .
when is is 0 it report a negative value instead of positive for grid power .

**Comment by Tof973** [comment]
Very good job anyway !

**Comment by rjpearce** [comment]
Thanks for raising this. Can you send me a screenshot or copy and paste some values? 

It can be difficult trying to aggregate values from different registers as the read requests are made separately. I'm currently exploring an alternative approach to read all the values.

**Comment by Tof973** [comment]
I don't have an example right now. but yesterday at the end of the day , with the actual sofar-hyd-ep.json. If active_power = -10 or -20 (reported negative sometimes on my system) and load _power=800 then grid is  800 - (-20) = 820 instead of 800. Which make sens if active_power can really be negative (this i don't know, maybe only measurment error) .

Even stranger  case : if active_power is zero and load_power is 800 then grid is -800 ???   it look like grid = 800 - 0= -800.

I tried to modify the grid in json inverting the active_power and load_power in the substract , and also invert : (chaged to false), witch gives  as follows. Until now i didn't see any problems, i will report if the same occure tonight.
I suspect something wrong in the substract calculation or even may be in the actual size of the numbers (like wrong type of int read from registers (?) .. well i don't really know) .

I am testing this (as a workaround): 
			{
			"name": "grid",
			"aggregate": [
"load_power",
"active_power"
			],
			"agg_function": "subtract",
"invert": false,
			"ha": {
				"name": "Sofar:Grid power",
				"unique_id": "sofar_grid_power",
				"device_class": "power",
				"unit_of_measurement": "W",
				"state_class": "measurement",
				"icon": "mdi:flash"
			}
		},

**Comment by Tof973** [comment]
I realized that i  forgot to confirme that it work now with the grid calculation changes. Thanks for your last commit, and work!
